name: push-workflow
on: [push]
jobs:
  build: Build the environment 
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nose black wandb
        sudo apt-get install -y libsndfile1-dev
    - name: Run all unit tests
      run: nosetests
    - name: Check formatting using Black
      run: black --check --diff training.py test_audionet.py
